"""Read-only, local-first iMessage relay parsing contracts."""

from .contracts import (
    Attachment,
    AttachmentAvailability,
    AttachmentComponent,
    AttachmentComponentRole,
    Direction,
    EventKind,
    MediaCategory,
    MessageEvent,
    ParseIssue,
    ReactionEvent,
    ReactionKind,
    ScanBatch,
    Sender,
    SenderKind,
)
from .errors import (
    AttributedBodyError,
    CursorConflictError,
    IMessageParserError,
    RelayStateError,
    SourceDatabaseError,
    SourceRecordError,
    SourceSchemaError,
    StateClosedError,
    StateConfigError,
    StateDatabaseError,
    StateIntegrityError,
    StateSchemaError,
    StateSecurityError,
    StateTransitionError,
    UnsafeAttachmentPathError,
)
from .reader import MessagesReader, open_read_only_database
from .state import (
    AttemptLease,
    AttemptOutcome,
    DeliveryAttemptRecord,
    QueueEntry,
    QueueStatus,
    RelayStateStore,
    RetryPolicy,
    StateSummary,
    StoredIssue,
)
from .state_config import RelayStateConfig, load_state_config
from .timestamps import apple_nanoseconds_to_datetime, apple_seconds_to_datetime

__all__ = [
    "Attachment",
    "AttachmentAvailability",
    "AttachmentComponent",
    "AttachmentComponentRole",
    "AttributedBodyError",
    "AttemptLease",
    "AttemptOutcome",
    "CursorConflictError",
    "DeliveryAttemptRecord",
    "Direction",
    "EventKind",
    "IMessageParserError",
    "MediaCategory",
    "MessageEvent",
    "MessagesReader",
    "ParseIssue",
    "ReactionEvent",
    "ReactionKind",
    "QueueEntry",
    "QueueStatus",
    "RelayStateError",
    "RelayStateConfig",
    "RelayStateStore",
    "RetryPolicy",
    "ScanBatch",
    "Sender",
    "SenderKind",
    "SourceDatabaseError",
    "SourceRecordError",
    "SourceSchemaError",
    "StateClosedError",
    "StateConfigError",
    "StateDatabaseError",
    "StateIntegrityError",
    "StateSchemaError",
    "StateSecurityError",
    "StateSummary",
    "StateTransitionError",
    "StoredIssue",
    "UnsafeAttachmentPathError",
    "apple_nanoseconds_to_datetime",
    "apple_seconds_to_datetime",
    "load_state_config",
    "open_read_only_database",
]
