"""Standalone Stage 4–7 kiosk-side iMessage relay receiver."""

from .auth import AUTH_SCHEME, AuthenticationError, RequestAuthenticator, sign_request
from .config import ReceiverConfig, ReceiverConfigError, load_receiver_config
from .protocol import (
    ATTACHMENT_CHUNK_PATH_PREFIX,
    ATTACHMENT_SESSION_PATH,
    EVENT_PATH,
    MAX_ATTACHMENT_BYTES,
    MAX_ATTACHMENT_CHUNK_BYTES,
    MAX_RECONCILIATION_CANDIDATES,
    PROTOCOL_VERSION,
    RECONCILIATION_PATH,
    ProtocolError,
    ReconciliationCandidate,
    ReconciliationReceipt,
    ValidatedEnvelope,
    ValidatedAttachmentChunkResponse,
    ValidatedUploadSessionRequest,
    ValidatedUploadSessionResponse,
    attachment_chunk_path,
    attachment_chunk_response_body,
    decode_attachment_chunk_path,
    decode_attachment_chunk_response,
    ValidatedReconciliationRequest,
    ValidatedReconciliationResponse,
    decode_event_envelope,
    decode_reconciliation_request,
    decode_reconciliation_response,
    decode_upload_session_request,
    decode_upload_session_response,
    encode_event_envelope,
    encode_reconciliation_request,
    event_wire_digest,
    event_to_wire_mapping,
    reconciliation_response_body,
    upload_session_response_body,
)
from .server import ReceiverApplication, ReceiverServer, build_server
from .store import (
    AttachmentChunkResult,
    AttachmentUploadSession,
    IngestResult,
    ReceiverStateStore,
    ReceiverStoreError,
    StoredAttachment,
)

__all__ = [
    "AUTH_SCHEME",
    "ATTACHMENT_CHUNK_PATH_PREFIX",
    "ATTACHMENT_SESSION_PATH",
    "AttachmentChunkResult",
    "AttachmentUploadSession",
    "AuthenticationError",
    "EVENT_PATH",
    "IngestResult",
    "MAX_RECONCILIATION_CANDIDATES",
    "MAX_ATTACHMENT_BYTES",
    "MAX_ATTACHMENT_CHUNK_BYTES",
    "PROTOCOL_VERSION",
    "RECONCILIATION_PATH",
    "ProtocolError",
    "ReconciliationCandidate",
    "ReconciliationReceipt",
    "ReceiverApplication",
    "ReceiverConfig",
    "ReceiverConfigError",
    "ReceiverServer",
    "ReceiverStateStore",
    "ReceiverStoreError",
    "RequestAuthenticator",
    "ValidatedEnvelope",
    "ValidatedAttachmentChunkResponse",
    "ValidatedUploadSessionRequest",
    "ValidatedUploadSessionResponse",
    "StoredAttachment",
    "attachment_chunk_path",
    "attachment_chunk_response_body",
    "ValidatedReconciliationRequest",
    "ValidatedReconciliationResponse",
    "build_server",
    "decode_event_envelope",
    "decode_attachment_chunk_path",
    "decode_attachment_chunk_response",
    "decode_reconciliation_request",
    "decode_reconciliation_response",
    "decode_upload_session_request",
    "decode_upload_session_response",
    "encode_event_envelope",
    "encode_reconciliation_request",
    "event_wire_digest",
    "event_to_wire_mapping",
    "load_receiver_config",
    "reconciliation_response_body",
    "upload_session_response_body",
    "sign_request",
]
